baseURL = "http://ronanlevesque.fr"
title = "Front-end & Webdesign"
RemovePathAccents = true

[params]
  author = "Ronan Levesque"
  description = "Site de Ronan Levesque : Front-end et Webdesign. HTML5, CSS3, Responsive design, JavaScript..."

[permalinks]
  articles = "/articles/:title/"
