import cx from 'classnames';
import { Roboto } from 'next/font/google';

import '../globals.css';

const roboto = Roboto({
  style: ['normal', 'italic'],
  subsets: ['latin'],
  weight: ['400', '400', '500', '700'],
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children, lang = 'en' }) {
  return (
    <html lang={lang}>
      <body className={cx(roboto.className, 'm-0 bg-blackPearl ~px-12/20')}>
        <div className="m-auto max-w-1200">{children}</div>
      </body>
    </html>
  );
}
